export const LIST_PRODUCT = 'LIST_PRODUCT';
export const LOADING = 'LOADING';
export const AUTH_LOADING = 'AUTH_LOADING';
export const LOADER = 'LOADER';

export const REMOVE_FROM_LIST= 'REMOVE_FROM_LIST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

// APP MESSAGE
export const SUCCESS_MESSAGE= "SUCCESS_MESSAGE";
export const FAILED_MESSAGE = 'FAILED_MESSAGE';
export const INVALID_CREDENTAIL = "INVALID_CREDENTAIL";
export const SERVER_ERROR = "SERVER_ERROR";

// APP
export const LIST_MARKET = "LIST_MARKET";
export const LIST_STORE = "LIST_STORE";
export const LIST_CATEGORY = "LIST_CATEGORY";
export const LIST_PRODUCT_CATEGORY = "LIST_PRODUCT_CATEGORY";
export const LIST_CHOICE_PRODUCT = "LIST_CHOICE_PRODUCT";
// Cart
export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const ADD_QUANTITY_BY_ONE = "ADD_QUANTITY_BY_ONE";



// CATEGORY PRODUCT 
export const ADD_UPDATE_PRODUCT_CART = "ADD_UPDATE_PRODUCT_CART";






